# Generated by Django 5.0.1 on 2025-05-15 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmd",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2025, 5, 15, 14, 5, 17, 187370)
            ),
        ),
    ]
