# Generated by Django 5.0.1 on 2025-05-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cmd_date"),
    ]

    operations = []
