# Generated by Django 5.0.1 on 2025-05-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20250518_1655"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cmd",
        ),
    ]
