# Generated by Django 5.0.1 on 2025-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_delete_cmd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Awb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awb", models.CharField(max_length=16)),
            ],
        ),
    ]
